[[entries.'app\Actions\Fortify\PasswordValidationRules.php'.issues]]
code = "trait-name"
start_line = 8
end_line = 8

[[entries.'app\Actions\GenerateStatic\DeleteUnrelatedTags.php'.issues]]
code = "no-empty"
start_line = 24
end_line = 24

[[entries.'app\Actions\SendSNS\Article\GetArticleParam.php'.issues]]
code = "parameter-type"
start_line = 27
end_line = 27

[[entries.'app\Actions\SendSNS\Article\ToOneSignal.php'.issues]]
code = "no-redundant-nullsafe"
start_line = 33
end_line = 33

[[entries.'app\Casts\ToArticleContents.php'.issues]]
code = "parameter-type"
start_line = 28
end_line = 28

[[entries.'app\Casts\ToArticleContents.php'.issues]]
code = "parameter-type"
start_line = 28
end_line = 28

[[entries.'app\Casts\ToArticleContents.php'.issues]]
code = "parameter-type"
start_line = 28
end_line = 28

[[entries.'app\Casts\ToArticleContents.php'.issues]]
code = "parameter-type"
start_line = 28
end_line = 28

[[entries.'app\Casts\ToArticleContents.php'.issues]]
code = "parameter-type"
start_line = 51
end_line = 51

[[entries.'app\Casts\ToArticleContents.php'.issues]]
code = "parameter-type"
start_line = 51
end_line = 51

[[entries.'app\Casts\ToArticleContents.php'.issues]]
code = "parameter-type"
start_line = 51
end_line = 51

[[entries.'app\Casts\ToArticleContents.php'.issues]]
code = "parameter-type"
start_line = 51
end_line = 51

[[entries.'app\Casts\ToProfileData.php'.issues]]
code = "parameter-type"
start_line = 24
end_line = 24

[[entries.'app\Casts\ToProfileData.php'.issues]]
code = "parameter-type"
start_line = 24
end_line = 24

[[entries.'app\Casts\ToProfileData.php'.issues]]
code = "parameter-type"
start_line = 24
end_line = 24

[[entries.'app\Casts\ToProfileData.php'.issues]]
code = "parameter-type"
start_line = 24
end_line = 24

[[entries.'app\Casts\ToProfileData.php'.issues]]
code = "parameter-type"
start_line = 42
end_line = 42

[[entries.'app\Casts\ToProfileData.php'.issues]]
code = "parameter-type"
start_line = 42
end_line = 42

[[entries.'app\Casts\ToProfileData.php'.issues]]
code = "parameter-type"
start_line = 42
end_line = 42

[[entries.'app\Casts\ToProfileData.php'.issues]]
code = "parameter-type"
start_line = 42
end_line = 42

[[entries.'app\Channels\BaseChannel.php'.issues]]
code = "class-name"
start_line = 6
end_line = 6

[[entries.'app\Console\Commands\LangJsonExportCommand.php'.issues]]
code = "explicit-octal"
start_line = 44
end_line = 44

[[entries.'app\Exceptions\Handler.php'.issues]]
code = "parameter-type"
start_line = 42
end_line = 42

[[entries.'app\Exceptions\Handler.php'.issues]]
code = "return-type"
start_line = 41
end_line = 45

[[entries.'app\Exceptions\InvalidRedirectUrlException.php'.issues]]
code = "no-empty-comment"
start_line = 10
end_line = 10

[[entries.'app\Http\Controllers\Controller.php'.issues]]
code = "class-name"
start_line = 14
end_line = 14

[[entries.'app\Http\Controllers\Front\FrontController.php'.issues]]
code = "no-request-all"
start_line = 121
end_line = 121

[[entries.'app\Http\Controllers\Front\FrontController.php'.issues]]
code = "too-many-methods"
start_line = 21
end_line = 165

[[entries.'app\Http\Requests\Article\BaseRequest.php'.issues]]
code = "class-name"
start_line = 11
end_line = 11

[[entries.'app\Listeners\Article\OnArticleUpdated.php'.issues]]
code = "no-else-clause"
start_line = 34
end_line = 36

[[entries.'app\Models\Article.php'.issues]]
code = "cyclomatic-complexity"
start_line = 37
end_line = 644

[[entries.'app\Models\Article.php'.issues]]
code = "identity-comparison"
start_line = 231
end_line = 231

[[entries.'app\Models\Article.php'.issues]]
code = "identity-comparison"
start_line = 253
end_line = 253

[[entries.'app\Models\Article.php'.issues]]
code = "identity-comparison"
start_line = 512
end_line = 512

[[entries.'app\Models\Article.php'.issues]]
code = "identity-comparison"
start_line = 541
end_line = 541

[[entries.'app\Models\Article.php'.issues]]
code = "parameter-type"
start_line = 231
end_line = 231

[[entries.'app\Models\Article.php'.issues]]
code = "parameter-type"
start_line = 242
end_line = 242

[[entries.'app\Models\Article.php'.issues]]
code = "parameter-type"
start_line = 248
end_line = 248

[[entries.'app\Models\Article.php'.issues]]
code = "parameter-type"
start_line = 253
end_line = 253

[[entries.'app\Models\Article.php'.issues]]
code = "parameter-type"
start_line = 364
end_line = 364

[[entries.'app\Models\Article.php'.issues]]
code = "parameter-type"
start_line = 388
end_line = 388

[[entries.'app\Models\Article.php'.issues]]
code = "parameter-type"
start_line = 400
end_line = 400

[[entries.'app\Models\Article.php'.issues]]
code = "parameter-type"
start_line = 412
end_line = 412

[[entries.'app\Models\Article.php'.issues]]
code = "parameter-type"
start_line = 512
end_line = 512

[[entries.'app\Models\Article.php'.issues]]
code = "parameter-type"
start_line = 541
end_line = 541

[[entries.'app\Models\Article.php'.issues]]
code = "parameter-type"
start_line = 561
end_line = 561

[[entries.'app\Models\Article.php'.issues]]
code = "parameter-type"
start_line = 571
end_line = 571

[[entries.'app\Models\Article.php'.issues]]
code = "parameter-type"
start_line = 581
end_line = 581

[[entries.'app\Models\Article.php'.issues]]
code = "return-type"
start_line = 364
end_line = 367

[[entries.'app\Models\Article.php'.issues]]
code = "return-type"
start_line = 388
end_line = 388

[[entries.'app\Models\Article.php'.issues]]
code = "return-type"
start_line = 400
end_line = 400

[[entries.'app\Models\Article.php'.issues]]
code = "return-type"
start_line = 412
end_line = 412

[[entries.'app\Models\Article.php'.issues]]
code = "return-type"
start_line = 509
end_line = 513

[[entries.'app\Models\Article.php'.issues]]
code = "return-type"
start_line = 518
end_line = 520

[[entries.'app\Models\Article.php'.issues]]
code = "return-type"
start_line = 537
end_line = 545

[[entries.'app\Models\Article.php'.issues]]
code = "return-type"
start_line = 560
end_line = 562

[[entries.'app\Models\Article.php'.issues]]
code = "return-type"
start_line = 570
end_line = 572

[[entries.'app\Models\Article.php'.issues]]
code = "return-type"
start_line = 580
end_line = 582

[[entries.'app\Models\Article.php'.issues]]
code = "strict-behavior"
start_line = 490
end_line = 490

[[entries.'app\Models\Article.php'.issues]]
code = "too-many-methods"
start_line = 37
end_line = 644

[[entries.'app\Models\Attachment.php'.issues]]
code = "parameter-type"
start_line = 166
end_line = 166

[[entries.'app\Models\Attachment.php'.issues]]
code = "return-type"
start_line = 80
end_line = 80

[[entries.'app\Models\Attachment.php'.issues]]
code = "return-type"
start_line = 121
end_line = 126

[[entries.'app\Models\Attachment.php'.issues]]
code = "return-type"
start_line = 131
end_line = 131

[[entries.'app\Models\Attachment.php'.issues]]
code = "return-type"
start_line = 136
end_line = 136

[[entries.'app\Models\Attachment.php'.issues]]
code = "return-type"
start_line = 141
end_line = 141

[[entries.'app\Models\Attachment.php'.issues]]
code = "too-many-methods"
start_line = 19
end_line = 170

[[entries.'app\Models\BulkZip.php'.issues]]
code = "parameter-type"
start_line = 51
end_line = 51

[[entries.'app\Models\Contents\Content.php'.issues]]
code = "class-name"
start_line = 6
end_line = 6

[[entries.'app\Models\Contents\Sections\Section.php'.issues]]
code = "class-name"
start_line = 6
end_line = 6

[[entries.'app\Models\Contents\Sections\SectionImage.php'.issues]]
code = "no-shorthand-ternary"
start_line = 17
end_line = 17

[[entries.'app\Models\Tag.php'.issues]]
code = "parameter-type"
start_line = 75
end_line = 75

[[entries.'app\Models\Tag.php'.issues]]
code = "return-type"
start_line = 75
end_line = 75

[[entries.'app\Models\User.php'.issues]]
code = "parameter-type"
start_line = 75
end_line = 75

[[entries.'app\Models\User.php'.issues]]
code = "parameter-type"
start_line = 230
end_line = 230

[[entries.'app\Models\User.php'.issues]]
code = "too-many-methods"
start_line = 27
end_line = 244

[[entries.'app\Models\User\Profile.php'.issues]]
code = "no-redundant-method-override"
start_line = 87
end_line = 91

[[entries.'app\Models\User\Profile.php'.issues]]
code = "return-type"
start_line = 60
end_line = 67

[[entries.'app\Models\User\ProfileData.php'.issues]]
code = "no-else-clause"
start_line = 25
end_line = 27

[[entries.'app\Notifications\MFASetupRecovered.php'.issues]]
code = "return-type"
start_line = 30
end_line = 35

[[entries.'app\Notifications\ResetPassword.php'.issues]]
code = "return-type"
start_line = 39
end_line = 45

[[entries.'app\Notifications\SendSNSNotification.php'.issues]]
code = "class-name"
start_line = 14
end_line = 14

[[entries.'app\Notifications\SendSNSNotification.php'.issues]]
code = "return-type"
start_line = 29
end_line = 29

[[entries.'app\Notifications\VerifyEmail.php'.issues]]
code = "parameter-type"
start_line = 23
end_line = 23

[[entries.'app\Notifications\VerifyEmail.php'.issues]]
code = "parameter-type"
start_line = 35
end_line = 35

[[entries.'app\Notifications\VerifyEmail.php'.issues]]
code = "return-type"
start_line = 22
end_line = 26

[[entries.'app\Notifications\VerifyEmail.php'.issues]]
code = "return-type"
start_line = 34
end_line = 41

[[entries.'app\Policies\BasePolicy.php'.issues]]
code = "class-name"
start_line = 10
end_line = 10

[[entries.'app\Providers\DIServiceProvider.php'.issues]]
code = "parameter-type"
start_line = 53
end_line = 53

[[entries.'app\Providers\DIServiceProvider.php'.issues]]
code = "parameter-type"
start_line = 60
end_line = 60

[[entries.'app\Providers\DIServiceProvider.php'.issues]]
code = "parameter-type"
start_line = 69
end_line = 69

[[entries.'app\Providers\DIServiceProvider.php'.issues]]
code = "parameter-type"
start_line = 84
end_line = 84

[[entries.'app\Providers\DIServiceProvider.php'.issues]]
code = "parameter-type"
start_line = 94
end_line = 94

[[entries.'app\Providers\DIServiceProvider.php'.issues]]
code = "parameter-type"
start_line = 100
end_line = 100

[[entries.'app\Providers\DIServiceProvider.php'.issues]]
code = "return-type"
start_line = 34
end_line = 45

[[entries.'app\Providers\FortifyServiceProvider.php'.issues]]
code = "no-empty-comment"
start_line = 22
end_line = 22

[[entries.'app\Providers\FortifyServiceProvider.php'.issues]]
code = "return-type"
start_line = 33
end_line = 39

[[entries.'app\Providers\FortifyServiceProvider.php'.issues]]
code = "return-type"
start_line = 41
end_line = 43

[[entries.'app\Providers\GoogleServiceProvider.php'.issues]]
code = "return-type"
start_line = 18
end_line = 25

[[entries.'app\Providers\RouteServiceProvider.php'.issues]]
code = "parameter-type"
start_line = 32
end_line = 32

[[entries.'app\Providers\RouteServiceProvider.php'.issues]]
code = "return-type"
start_line = 32
end_line = 34

[[entries.'app\Providers\RouteServiceProvider.php'.issues]]
code = "return-type"
start_line = 39
end_line = 39

[[entries.'app\Providers\RouteServiceProvider.php'.issues]]
code = "return-type"
start_line = 46
end_line = 46

[[entries.'app\Providers\TwitterOauthProvider.php'.issues]]
code = "return-type"
start_line = 20
end_line = 27

[[entries.'app\Repositories\ArticleRepository.php'.issues]]
code = "no-else-clause"
start_line = 78
end_line = 80

[[entries.'app\Repositories\ArticleRepository.php'.issues]]
code = "parameter-type"
start_line = 33
end_line = 33

[[entries.'app\Repositories\ArticleRepository.php'.issues]]
code = "parameter-type"
start_line = 116
end_line = 116

[[entries.'app\Repositories\ArticleRepository.php'.issues]]
code = "parameter-type"
start_line = 119
end_line = 119

[[entries.'app\Repositories\ArticleRepository.php'.issues]]
code = "parameter-type"
start_line = 131
end_line = 131

[[entries.'app\Repositories\ArticleRepository.php'.issues]]
code = "parameter-type"
start_line = 144
end_line = 144

[[entries.'app\Repositories\ArticleRepository.php'.issues]]
code = "parameter-type"
start_line = 243
end_line = 243

[[entries.'app\Repositories\ArticleRepository.php'.issues]]
code = "parameter-type"
start_line = 293
end_line = 293

[[entries.'app\Repositories\ArticleRepository.php'.issues]]
code = "return-type"
start_line = 33
end_line = 33

[[entries.'app\Repositories\ArticleRepository.php'.issues]]
code = "return-type"
start_line = 116
end_line = 119

[[entries.'app\Repositories\ArticleRepository.php'.issues]]
code = "return-type"
start_line = 119
end_line = 119

[[entries.'app\Repositories\ArticleRepository.php'.issues]]
code = "too-many-methods"
start_line = 17
end_line = 409

[[entries.'app\Repositories\BaseRepository.php'.issues]]
code = "class-name"
start_line = 22
end_line = 22

[[entries.'app\Repositories\BaseRepository.php'.issues]]
code = "parameter-type"
start_line = 49
end_line = 49

[[entries.'app\Repositories\BaseRepository.php'.issues]]
code = "too-many-methods"
start_line = 22
end_line = 190

[[entries.'app\Repositories\TagRepository.php'.issues]]
code = "parameter-type"
start_line = 61
end_line = 61

[[entries.'app\Repositories\TagRepository.php'.issues]]
code = "return-type"
start_line = 61
end_line = 61

[[entries.'app\Repositories\UserRepository.php'.issues]]
code = "parameter-type"
start_line = 63
end_line = 63

[[entries.'app\Repositories\UserRepository.php'.issues]]
code = "parameter-type"
start_line = 81
end_line = 81

[[entries.'app\Repositories\UserRepository.php'.issues]]
code = "parameter-type"
start_line = 99
end_line = 99

[[entries.'app\Repositories\UserRepository.php'.issues]]
code = "return-type"
start_line = 81
end_line = 85

[[entries.'app\Rules\UniqueSlugByUser.php'.issues]]
code = "no-else-clause"
start_line = 48
end_line = 50

[[entries.'app\Services\FileInfo\Extractors\Extractor.php'.issues]]
code = "interface-name"
start_line = 6
end_line = 6

[[entries.'app\Services\FileInfo\Extractors\PakBinary.php'.issues]]
code = "no-else-clause"
start_line = 43
end_line = 45

[[entries.'app\Services\FileInfo\Extractors\PakExtractor.php'.issues]]
code = "no-shorthand-ternary"
start_line = 59
end_line = 59

[[entries.'app\Services\FileInfo\Extractors\PakExtractor.php'.issues]]
code = "no-shorthand-ternary"
start_line = 60
end_line = 60

[[entries.'app\Services\FileInfo\Extractors\TabExtractor.php'.issues]]
code = "no-else-clause"
start_line = 51
end_line = 54

[[entries.'app\Services\FileInfo\TextService.php'.issues]]
code = "no-shorthand-ternary"
start_line = 17
end_line = 17

[[entries.'app\Services\FileInfo\ZipArchiveParser.php'.issues]]
code = "no-shorthand-ternary"
start_line = 51
end_line = 51

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 47
end_line = 47

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 58
end_line = 58

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 69
end_line = 69

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 80
end_line = 80

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 91
end_line = 91

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 102
end_line = 102

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 112
end_line = 112

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 122
end_line = 122

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 132
end_line = 132

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 142
end_line = 142

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 152
end_line = 152

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 162
end_line = 162

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 172
end_line = 172

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 182
end_line = 182

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 192
end_line = 192

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 202
end_line = 202

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 212
end_line = 212

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 222
end_line = 222

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 232
end_line = 232

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 242
end_line = 242

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 252
end_line = 252

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "no-redundant-string-concat"
start_line = 262
end_line = 262

[[entries.'app\Services\Front\MetaOgpService.php'.issues]]
code = "too-many-methods"
start_line = 11
end_line = 276

[[entries.'app\Services\Google\Recaptcha\RecaptchaException.php'.issues]]
code = "class-name"
start_line = 8
end_line = 8

[[entries.'app\Services\Twitter\Exceptions\PKCETokenException.php'.issues]]
code = "class-name"
start_line = 6
end_line = 6

[[entries.'app\Services\Twitter\PKCEService.php'.issues]]
code = "excessive-parameter-list"
start_line = 16
end_line = 23

[[entries.'app\Services\Twitter\PKCEService.php'.issues]]
code = "no-empty-catch-clause"
start_line = 139
end_line = 140

[[entries.'app\Traits\Slugable.php'.issues]]
code = "trait-name"
start_line = 13
end_line = 13

[[entries.'database\seeders\AttachmentFileSizeSeeder.php'.issues]]
code = "parameter-type"
start_line = 16
end_line = 16
