name: Auto Package Update

on:
  schedule:
    - cron: "0 0 * * 0"  # 毎週日曜日
  workflow_dispatch:

jobs:
  update:
    name: Update Dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          # Must be used to trigger workflow after push
          token: ${{ secrets.ACCESS_TOKEN }}

      - run: php -r "copy('.env.ci', '.env');"
      - uses: ./.github/actions/php
      - uses: ./.github/actions/nodejs

      - name: Update PHP dependencies
        run: |
          composer update
          composer bump
          composer update

      - name: Update Node.js dependencies
        run: npm update

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto update dependencies"
          commit_author: "GitHub Actions <actions@github.com>"
